### ISSUE TITLE
q1 and q3 return NaN on a single data point

### ISSUE THREAD

**Issue by RandScullard** [angusgibbs/statsjs#7]
The min, max, and median functions work fine on an array with a single data point, but the q1 and q3 functions return NaN:

    var foo = stats([42])
    foo.min() // 42
    foo.max() // 42
    foo.median() // 42
    foo.q1() // NaN
    foo.q3() // NaN

I would have expected them to return 42 in this case.

**Comment by angusgibbs** [comment]
Good catch! This has been fixed and published as v1.0.7.
